sudo: required
notifications:
  email:
    on_success: never
    on_failure: never
matrix:
  include:
#    - langage: python
#      python: 2.7
#      os: linux
#      dist: trusty

    - langage: python
      python: 3.4
      os: linux
      dist: trusty

    - langage: python
      python: 3.5
      os: linux
      dist: trusty

    - langage: python
      python: 3.6
      os: linux
      dist: trusty

install: # command to install dependencies
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install python3-pip; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libgmp-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libmpfr-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libmpc-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libppl-dev; fi
  - pip3 install --user 'Cython==0.26';
  - pip3 install --user git+https://github.com/aleaxit/gmpy.git@gmpy2-2.1.0a0 --no-index --verbose;
  - pip3 install --user cysignals;
  - pip3 install --user git+https://github.com/jesusjda/pplpy --no-index --verbose
  - pip3 install --user z3-solver
  - pip3 install --user git+https://github.com/jesusjda/pyLPi --verbose --no-index;
  - pip3 install --user pydotplus
  - pip3 install --user pydot
  - pip3 install --user networkx
  - pip3 install --user arpeggio
  - pip3 install --user pyleri
  - mkdir -p /tmp/pyeiol
  - pushd /tmp/pyeiol
  - git clone https://github.com/abstools/easyinterface.git .
  - git checkout develop
  - cd ./outputlanguage/python
  - pip3 install --user .
  - popd
  - pip3 install --user git+https://github.com/jesusjda/pyParser --verbose --no-index;
  - pip3 install . --user --verbose --no-index;
script:
  - echo "DONE!"
